//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum eEntityStatus {
	Active = 0,
	Deleted = 99
}
export enum eResource {
	Company = 0,
	User = 1,
	Category = 2,
	Item = 3,
	ItemEvent = 4,
	Instance = 5,
	InstanceEvent = 6
}
export enum ePermission {
	View = 1,
	Create = 2,
	Update = 4,
	Remove = 8,
	Delete = 16
}
export enum eItemType {
	Element = 0,
	Composite = 1
}
