//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum eEntityStatus {
	Active = 0,
	Deleted = 99
}
export enum ePermission {
	Read = 1,
	Write = 2,
	Modify = 4,
	Remove = 8
}
export enum ePermissionSection {
	User = 0,
	Category = 1,
	Element = 2,
	Event = 3
}
